# The build-stage image:
FROM continuumio/miniconda3:4.10.3 AS build

# Install conda-pack:
RUN conda config --set channel_priority strict && \
    conda install -c conda-forge conda-pack && \
    conda create --name hydra -c conda-forge -c bioconda -c defaults \
    bcftools=1.3.1 \
    blast=2.2.31 \
    bwa=0.7.15 \
    cutadapt=1.8.1 \
    fastqc=0.11.2 \
    gatk4=4.1.7 \
    gawk=5.1.0 \
    gzip=1.12 \
    openjdk=8.0.332 \
    parallel=20230122 \
    perl-bioperl=1.6.924-0 \
    pigz=2.6 \
    primerclip=0.3.8 \
    samtools=1.9 \
    trimmomatic=0.32 && \
    conda-pack -n hydra -o /tmp/env.tar


# Use conda-pack to create a standalone enviornment
# in /venv:

WORKDIR /venv 
RUN tar xf /tmp/env.tar

# We've put venv in same path it'll be in final image,
# so now fix up paths:
RUN /venv/bin/conda-unpack

# The runtime-stage image; we can use Debian as the
# base image since the Conda env also includes Python
# for us.
FROM ubuntu:20.04 AS runtime

LABEL maintainer="patrik.smeds@scilifelab.uu.se"
LABEL version=1.0.0
LABEL annovar=2015Mars22
LABEL bcftools=1.3.1
LABEL blast=2.2.31
LABEL bwa=0.7.15
LABEL cutadapt=1.8.1
LABEL fastqc=0.11.2
LABEL gatk4=4.1.0
LABEL gawk=5.1.0
LABEL gzip=1.12 
LABEL openjdk=8.0.332
LABEL parallel=20230122
LABEL perl-bioperl=1.6.924-0
LABEL pigz=2.6
LABEL pindel=0.2.5a8
LABEL primerclip=0.3.8
LABEL python2-minimal=apt-version
LABEL rsync=apt-version
LABEL samtools=1.9
LABEL trimmomatic=0.32 

RUN rm /usr/local/man
COPY --from=build /venv/ /usr/local/

RUN apt-get update && \
    apt-get install -y  --no-install-recommends python2-minimal rsync libfreetype6 fontconfig fonts-dejavu python2.7-argparse language-pack-sv python2.7-pyparsing wget ca-certificates

ENV FONTCONFIG_PATH="/etc/fonts"
ENV FONTCONFIG_FILE="/etc/fonts/fonts.conf"
#    rm /usr/local/bin/python && \
#    update-alternatives --install /usr/local/bin/python python /usr/bin/python2 1

RUN mkdir /jar && \
    locale-gen sv_SE.utf8 && \
    update-locale LANG="sv_SE.UTF-8" LANGUAGE="sv_SE" LC_ALL="sv_SE.UTF-8" && \
    dpkg-reconfigure locales

COPY local_files/0.2.5a8 /pindel
COPY local_files/annovar /annovar
COPY bin/java/biostar84452.jar /jar/biostar84452.jar
COPY bin/java/SortSam.jar /jar/SortSam.jar
COPY local_files/trimmomatic-0.35.jar /jar/trimmomatic-0.35.jar
COPY local_files/jSNPmania-0.0.7-SNAPSHOT-amplicons_v4 /jSNPmania-0.0.7-SNAPSHOT-amplicons_v4


ENV PATH=$PATH:/pindel/bin

RUN wget https://bootstrap.pypa.io/pip/2.7/get-pip.py && python2 get-pip.py

